apps/authentication/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin

from apps import db, login_manager

from apps.authentication.util import hash_pass

class Users(db.Model, UserMixin):

    __tablename__ = 'Users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(64), unique=True)
    password = db.Column(db.LargeBinary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass(value)  # we need bytes here (not plain str)

            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return Users.query.filter_by(id=id).first()


@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = Users.query.filter_by(username=username).first()
    return user if user else None

apps/authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import Email, DataRequired

# login and registration


class LoginForm(FlaskForm):
    username = StringField('Username',
                         id='username_login',
                         validators=[DataRequired()])
    password = PasswordField('Password',
                             id='pwd_login',
                             validators=[DataRequired()])


class CreateAccountForm(FlaskForm):
    username = StringField('Username',
                         id='username_create',
                         validators=[DataRequired()])
    email = StringField('Email',
                      id='email_create',
                      validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             id='pwd_create',
                             validators=[DataRequired()])

apps/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from importlib import import_module


db = SQLAlchemy()
login_manager = LoginManager()


def register_extensions(app):
    db.init_app(app)
    login_manager.init_app(app)


def register_blueprints(app):
    for module_name in ('authentication', 'home'):
        module = import_module('apps.{}.routes'.format(module_name))
        app.register_blueprint(module.blueprint)


def configure_database(app):

    @app.before_first_request
    def initialize_database():
        db.create_all()

    @app.teardown_request
    def shutdown_session(exception=None):
        db.session.remove()


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)
    register_extensions(app)
    register_blueprints(app)
    configure_database(app)
    return app

apps/authentication/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'authentication_blueprint',
    __name__,
    url_prefix=''
)

apps/authentication/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_user,
    logout_user
)

from apps import db, login_manager
from apps.authentication import blueprint
from apps.authentication.forms import LoginForm, CreateAccountForm
from apps.authentication.models import Users

from apps.authentication.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('authentication_blueprint.login'))

# Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:

        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = Users.query.filter_by(username=username).first()

        # Check the password
        if user and verify_pass(password, user.password):

            login_user(user)
            return redirect(url_for('authentication_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template('accounts/login.html',
                               msg='Wrong user or password',
                               form=login_form)

    if not current_user.is_authenticated:
        return render_template('accounts/login.html',
                               form=login_form)
    return redirect(url_for('home_blueprint.index'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username = request.form['username']
        email = request.form['email']

        # Check usename exists
        user = Users.query.filter_by(username=username).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Username already registered',
                                   success=False,
                                   form=create_account_form)

        # Check email exists
        user = Users.query.filter_by(email=email).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Email already registered',
                                   success=False,
                                   form=create_account_form)

        # else we can create the user
        user = Users(**request.form)
        db.session.add(user)
        db.session.commit()

        # Delete user from session
        logout_user()

        return render_template('accounts/register.html',
                               msg='User created successfully.',
                               success=True,
                               form=create_account_form)

    else:
        return render_template('accounts/register.html', form=create_account_form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('authentication_blueprint.login')) 

# Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('home/page-404.html'), 404


@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('home/page-500.html'), 500

apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from apps.home import blueprint
from flask import render_template, request
from flask_login import login_required
from jinja2 import TemplateNotFound


@blueprint.route('/index')
@login_required
def index():

    return render_template('home/index.html', segment='index')


@blueprint.route('/<template>')
@login_required
def route_template(template):

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None

apps/templates/accounts/login.html
{% extends "layouts/base-authentication.html" %}

{% block title %} Sign IN {% endblock title %}

<!-- Specific CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="peers ai-s fxw-nw h-100vh">
      <div class="d-n@sm- peer peer-greed h-100 pos-r bgr-n bgpX-c bgpY-c bgsz-cv" style='background-image: url("{{ config.ASSETS_ROOT }}/images/bg.jpg")'>
        <div class="pos-a centerXY">
          <div class="bgc-white bdrs-50p pos-r" style='width: 120px; height: 120px;'>
            <img class="pos-a centerXY" src="{{ config.ASSETS_ROOT }}/images/logo.png" alt="">
          </div>
        </div>
      </div>
      <div class="col-12 col-md-4 peer pX-40 pY-80 h-100 bgc-white scrollable pos-r" style='min-width: 320px;'>

        <h4 class="fw-300 c-grey-900 mB-40">Adminator - Login</h4>
        
        {% if msg %}
            <p class="fw-300 c-red-900 mB-40">{{ msg | safe }}</p>
        {% else %}
            <p class="fw-300 c-grey-900 mB-40">
              Add your credentials
            </p>
        {% endif %}

        <form method="post" action="">

          {{ form.hidden_tag() }}

          <div class="mb-3">
            <label class="text-normal text-dark form-label">Username</label>
            {{ form.username(placeholder="Username", class="form-control") }}
          </div>

          <div class="mb-3">
            <label class="text-normal text-dark form-label">Password</label>
            {{ form.password(placeholder="Password", class="form-control", type="password") }}
          </div>

          <div class="mb-3">
            <button type="submit" name="login" class="btn btn-primary">Login</button>

            &nbsp; &nbsp;
            <span class="text-small font-weight-semibold">Not a member?</span>
            <a href="{{ url_for('authentication_blueprint.register') }}" class="text-black text-small">Register</a>  
          </div>

        </form>
      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/accounts/register.html
{% extends "layouts/base-authentication.html" %}

{% block title %} Register {% endblock title %}

<!-- Specific CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="peers ai-s fxw-nw h-100vh">
      <div class="peer peer-greed h-100 pos-r bgr-n bgpX-c bgpY-c bgsz-cv" style='background-image: url("{{ config.ASSETS_ROOT }}/images/bg.jpg")'>
        <div class="pos-a centerXY">
          <div class="bgc-white bdrs-50p pos-r" style='width: 120px; height: 120px;'>
            <img class="pos-a centerXY" src="{{ config.ASSETS_ROOT }}/images/logo.png" alt="">
          </div>
        </div>
      </div>
      <div class="col-12 col-md-4 peer pX-40 pY-80 h-100 bgc-white scrollable pos-r" style='min-width: 320px;'>
        
        <h4 class="fw-300 c-grey-900 mB-40">Adminator - Register</h4>

        {% if msg %}
            <p class="fw-300 c-grey-900 mB-40">{{ msg | safe }}</p>
        {% else %}
            <p class="fw-300 c-grey-900 mB-40">
              Add your credentials
            </p>
        {% endif %}

        {% if success %}

        <div class="mb-3">
          <a href="{{ url_for('authentication_blueprint.login') }}" class="btn btn-primary">Sign IN</a>
        </div>

        {% else %}

        <form method="post" action="">

          {{ form.hidden_tag() }}

          <div class="mb-3">
            <label class="form-label" class="text-normal text-dark">Username</label>
            {{ form.username(placeholder="Username", class="form-control") }}
          </div>

          <div class="mb-3">
            <label class="form-label" class="text-normal text-dark">Email Address</label>
            {{ form.email(placeholder="eMail Address", class="form-control") }}
          </div>
          
          <div class="mb-3">
            <label class="form-label" class="text-normal text-dark">Password</label>
            {{ form.password(placeholder="Password", class="form-control", type="password") }}
          </div>
          
          <div class="mb-3">
            <button type="submit" name="register" class="btn btn-primary">Register</button>

            &nbsp; &nbsp;
            <span class="text-small font-weight-semibold">Have and account?</span>
            <a href="{{ url_for('authentication_blueprint.login') }}" class="text-black text-small">Login</a>  
          </div>
          
        </form>

        {% endif %} 

      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/blank.html
{% extends "layouts/base.html" %}

{% block title %} Blank Page {% endblock title %}

<!-- Specific CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <!-- ### $App Screen Content ### -->
  <main class='main-content bgc-grey-100'>
    <div id='mainContent'>
      <div class="full-container">

        <h1>Add content here</h1>

      </div>
    </div>
  </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/charts.html
{% extends "layouts/base.html" %}

{% block title %} Charts {% endblock title %}

<!-- Specific CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- ### $App Screen Content ### -->
    <main class='main-content bgc-grey-100'>
      <div id='mainContent'>
        <div class="row gap-20 masonry pos-r">
          <div class="masonry-sizer col-md-6 pos-a"></div>
          <div class="masonry-item col-md-6">
            <div class="bgc-white p-20 bd">
              <h6 class="c-grey-900">Line Chart</h6>
              <div class="mT-30">
                <canvas id="line-chart" height="220"></canvas>
              </div>
            </div>
          </div>
          <div class="masonry-item col-md-6">
            <div class="bgc-white p-20 bd">
              <h6 class="c-grey-900">Area Chart</h6>
              <div class="mT-30">
                <canvas id="area-chart" height="220"></canvas>
              </div>
            </div>
          </div>
          <div class="masonry-item col-md-6">
            <div class="bgc-white p-20 bd">
              <h6 class="c-grey-900">Scatter Chart</h6>
              <div class="mT-30">
                <canvas id="scatter-chart" height="220"></canvas>
              </div>
            </div>
          </div>
          <div class="masonry-item col-md-6">
            <div class="bgc-white p-20 bd">
              <h6 class="c-grey-900">Bar Chart</h6>
              <div class="mT-30">
                <canvas id="bar-chart" height="220"></canvas>
              </div>
            </div>
          </div>
          <div class="masonry-item col-md-6">
            <div class="bgc-white p-20 bd">
              <h6 class="c-grey-900">jQuery Sparkline</h6>
              <div class="mT-30">
                <div class="peers ai-c jc-sb fxw-nw bdB pY-15">
                  <div class="peer">
                    <span>Spark Line</span>
                  </div>
                  <div class="peer">
                    <span class="sparkline">&nbsp;</span>
                  </div>
                </div>
                <div class="peers ai-c jc-sb fxw-nw bdB pY-15">
                  <div class="peer">
                    <span>Spark Bar</span>
                  </div>
                  <div class="peer">
                    <span class="sparkbar">&nbsp;</span>
                  </div>
                </div>
                <div class="peers ai-c jc-sb fxw-nw bdB pY-15">
                  <div class="peer">
                    <span>Spark Tristate</span>
                  </div>
                  <div class="peer">
                    <span class="sparktri">&nbsp;</span>
                  </div>
                </div>
                <div class="peers ai-c jc-sb fxw-nw bdB pY-15">
                  <div class="peer">
                    <span>Spark Discrete</span>
                  </div>
                  <div class="peer">
                    <span class="sparkdisc">&nbsp;</span>
                  </div>
                </div>
                <div class="peers ai-c jc-sb fxw-nw bdB pY-15">
                  <div class="peer">
                    <span>Spark Bullet</span>
                  </div>
                  <div class="peer">
                    <span class="sparkbull">&nbsp;</span>
                  </div>
                </div>
                <div class="peers ai-c jc-sb fxw-nw pT-15">
                  <div class="peer">
                    <span>Spark Box</span>
                  </div>
                  <div class="peer">
                    <span class="sparkbox">&nbsp;</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="masonry-item col-md-6">
            <div class="bgc-white p-20 bd">
              <h6 class="c-grey-900">Easy Pie Charts</h6>
              <div class="mT-30">
                <div class="peers mT-20 fxw-nw@lg+ jc-sb ta-c gap-10">
                  <div class="peer">
                    <div class="easy-pie-chart" data-size='80' data-percent="75" data-bar-color='#f44336'>
                      <span></span>
                    </div>
                    <h6 class="fsz-sm">New Users</h6>
                  </div>
                  <div class="peer">
                    <div class="easy-pie-chart" data-size='80' data-percent="50" data-bar-color='#2196f3'>
                      <span></span>
                    </div>
                    <h6 class="fsz-sm">New Purchases</h6>
                  </div>
                  <div class="peer">
                    <div class="easy-pie-chart" data-size='80' data-percent="65" data-bar-color='#f44336'>
                      <span></span>
                    </div>
                    <h6 class="fsz-sm">New Customers</h6>
                  </div>
                  <div class="peer">
                    <div class="easy-pie-chart" data-size='80' data-percent="90" data-bar-color='#ff9800'>
                      <span></span>
                    </div>
                    <h6 class="fsz-sm">Bounce Rate</h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base-error.html" %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class='pos-a t-0 l-0 bgc-white w-100 h-100 d-f fxd-r fxw-w ai-c jc-c pos-r p-30'>
      <div class='mR-60'>
        <img alt='#' src='{{ config.ASSETS_ROOT }}/images/404.png' />
      </div>

      <div class='d-f jc-c fxd-c'>
        <h1 class='mB-30 fw-900 lh-1 c-red-500' style="font-size: 60px;">404</h1>
        <h3 class='mB-10 fsz-lg c-grey-900 tt-c'>Oops Page Not Found</h3>
        <p class='mB-30 fsz-def c-grey-700'>The page you are looking for does not exist or has been moved.</p>
        <div>
          <a href="index.html" type='primary' class='btn btn-primary'>Go to Home</a>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-500.html
{% extends "layouts/base-error.html" %}

{% block title %} Error 500 {% endblock title %}

<!-- Specific CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class='pos-a t-0 l-0 bgc-white w-100 h-100 d-f fxd-r fxw-w ai-c jc-c pos-r p-30'>
      <div class='mR-60'>
        <img alt='#' src='{{ config.ASSETS_ROOT }}/images/500.png' />
      </div>

      <div class='d-f jc-c fxd-c'>
        <h1 class='mB-30 fw-900 lh-1 c-red-500' style="font-size: 60px;">500</h1>
        <h3 class='mB-10 fsz-lg c-grey-900 tt-c'>Internal server error</h3>
        <p class='mB-30 fsz-def c-grey-700'>Something goes wrong with our servers, please try again later.</p>
        <div>
          <a href="index.html" type='primary' class='btn btn-primary'>Go to Home</a>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/vector-maps.html
{% extends "layouts/base.html" %}

{% block title %} UI Elements {% endblock title %}

<!-- Specific CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- ### $App Screen Content ### -->
    <main class='main-content bgc-grey-100'>
      <div id='mainContent'>
        <div class="container-fluid">
          <h4 class="c-grey-900 mT-10 mB-30">Vector Maps</h4>
          <div class="row">
            <div class="col-md-12">
              <div class="bgc-white bd bdrs-3 p-20 mB-20">
                <h6 class="c-grey-900 mB-20">Jquery Vector Maps</h6>
                <div id="world-map-marker"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/includes/footer.html
<footer class="bdT ta-c p-30 lh-0 fsz-sm c-grey-600">
    <span>
        &copy; Designed by Colorlib - Supported By <a href="https://appseed.us/" target="_blank">AppSeed</a>.
    </span>
</footer>

apps/templates/includes/navigation.html
<div class="header navbar">
    <div class="header-container">
      <ul class="nav-left">
        <li>
          <a id='sidebar-toggle' class="sidebar-toggle" href="javascript:void(0);">
            <i class="ti-menu"></i>
          </a>
        </li>
        <li class="search-box">
          <a class="search-toggle no-pdd-right" href="javascript:void(0);">
            <i class="search-icon ti-search pdd-right-10"></i>
            <i class="search-icon-close ti-close pdd-right-10"></i>
          </a>
        </li>
        <li class="search-input">
          <input class="form-control" type="text" placeholder="Search...">
        </li>
      </ul>
      <ul class="nav-right">
        <li class="notifications dropdown">
          <span class="counter bgc-red">3</span>
          <a href="" class="dropdown-toggle no-after" data-bs-toggle="dropdown">
            <i class="ti-bell"></i>
          </a>

          <ul class="dropdown-menu">
            <li class="pX-20 pY-15 bdB">
              <i class="ti-bell pR-10"></i>
              <span class="fsz-sm fw-600 c-grey-900">Notifications</span>
            </li>
            <li>
              <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
                <li>
                  <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                    <div class="peer mR-15">
                      <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
                    </div>
                    <div class="peer peer-greed">
                      <span>
                        <span class="fw-500">John Doe</span>
                        <span class="c-grey-600">liked your <span class="text-dark">post</span>
                        </span>
                      </span>
                      <p class="m-0">
                        <small class="fsz-xs">5 mins ago</small>
                      </p>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                    <div class="peer mR-15">
                      <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
                    </div>
                    <div class="peer peer-greed">
                      <span>
                        <span class="fw-500">Moo Doe</span>
                        <span class="c-grey-600">liked your <span class="text-dark">cover image</span>
                        </span>
                      </span>
                      <p class="m-0">
                        <small class="fsz-xs">7 mins ago</small>
                      </p>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                    <div class="peer mR-15">
                      <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
                    </div>
                    <div class="peer peer-greed">
                      <span>
                        <span class="fw-500">Lee Doe</span>
                        <span class="c-grey-600">commented on your <span class="text-dark">video</span>
                        </span>
                      </span>
                      <p class="m-0">
                        <small class="fsz-xs">10 mins ago</small>
                      </p>
                    </div>
                  </a>
                </li>
              </ul>
            </li>
            <li class="pX-20 pY-15 ta-c bdT">
              <span>
                <a href="" class="c-grey-600 cH-blue fsz-sm td-n">View All Notifications <i class="ti-angle-right fsz-xs mL-10"></i></a>
              </span>
            </li>
          </ul>
        </li>
        <li class="notifications dropdown">
          <span class="counter bgc-blue">3</span>
          <a href="" class="dropdown-toggle no-after" data-bs-toggle="dropdown">
            <i class="ti-email"></i>
          </a>

          <ul class="dropdown-menu">
            <li class="pX-20 pY-15 bdB">
              <i class="ti-email pR-10"></i>
              <span class="fsz-sm fw-600 c-grey-900">Emails</span>
            </li>
            <li>
              <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
                <li>
                  <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                    <div class="peer mR-15">
                      <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
                    </div>
                    <div class="peer peer-greed">
                      <div>
                        <div class="peers jc-sb fxw-nw mB-5">
                          <div class="peer">
                            <p class="fw-500 mB-0">John Doe</p>
                          </div>
                          <div class="peer">
                            <small class="fsz-xs">5 mins ago</small>
                          </div>
                        </div>
                        <span class="c-grey-600 fsz-sm">
                          Want to create your own customized data generator for your app...
                        </span>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                    <div class="peer mR-15">
                      <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
                    </div>
                    <div class="peer peer-greed">
                      <div>
                        <div class="peers jc-sb fxw-nw mB-5">
                          <div class="peer">
                            <p class="fw-500 mB-0">Moo Doe</p>
                          </div>
                          <div class="peer">
                            <small class="fsz-xs">15 mins ago</small>
                          </div>
                        </div>
                        <span class="c-grey-600 fsz-sm">
                          Want to create your own customized data generator for your app...
                        </span>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                    <div class="peer mR-15">
                      <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
                    </div>
                    <div class="peer peer-greed">
                      <div>
                        <div class="peers jc-sb fxw-nw mB-5">
                          <div class="peer">
                            <p class="fw-500 mB-0">Lee Doe</p>
                          </div>
                          <div class="peer">
                            <small class="fsz-xs">25 mins ago</small>
                          </div>
                        </div>
                        <span class="c-grey-600 fsz-sm">
                          Want to create your own customized data generator for your app...
                        </span>
                      </div>
                    </div>
                  </a>
                </li>
              </ul>
            </li>
            <li class="pX-20 pY-15 ta-c bdT">
              <span>
                <a href="email.html" class="c-grey-600 cH-blue fsz-sm td-n">View All Email <i class="fs-xs ti-angle-right ms-10"></i></a>
              </span>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-bs-toggle="dropdown">
            <div class="peer mR-10">
              <img class="w-2r bdrs-50p" src="https://randomuser.me/api/portraits/men/10.jpg" alt="">
            </div>
            <div class="peer">
              <span class="fsz-sm c-grey-900">John Doe</span>
            </div>
          </a>
          <ul class="dropdown-menu fsz-sm">
            <li>
              <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                <i class="ti-settings mR-10"></i>
                <span>Setting</span>
              </a>
            </li>
            <li>
              <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                <i class="ti-user mR-10"></i>
                <span>Profile</span>
              </a>
            </li>
            <li>
              <a href="email.html" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                <i class="ti-email mR-10"></i>
                <span>Messages</span>
              </a>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <a href="{{ url_for('authentication_blueprint.logout') }}" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                <i class="ti-power-off mR-10"></i>
                <span>Logout</span>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  